const courseData = {
  "68789a19935761547602aef3": {
    name: "ISP",
    lessons: {
      "ISP01": {
        title: "Introduction to Information Security & Data Protection",
        videoUrl: "https://intern-vista-work-space.s3.eu-north-1.amazonaws.com/e-learning/Module_1+Course+2+(1).mp4",
        content: [
          "What is Information Security?",
          "",
          "Information security is the practice of protecting digital and physical information from unauthorized access, use, disclosure, disruption, modification, or destruction.",
          ,
          "The Three Pillars of Information Security:",
          "Confidentiality - Ensuring information is accessible only to those authorized to have access",
          "Integrity - Safeguarding the accuracy and completeness of information and processing methods",
          "Availability - Ensuring that authorized users have access to information and associated assets when required",
          "",
          "Why is Data Protection Important?",
          "Protects personal privacy and maintains trust",
          "Prevents financial losses from data breaches",
          "Ensures compliance with legal and regulatory requirements",
          "Maintains competitive advantage and business reputation",
          "",
          "Everyone's Responsibility:",
          "Information security is not just the IT department's job - it's everyone's responsibility",
          "Every employee handles sensitive information daily",
          "A single security incident can affect the entire organization",
          "",
          "Basic Employee Responsibilities:",
          "Keep your knowledge of data protection policies updated",
          "Handle all information (customer data, financial records, strategic plans) with care",
          "Report security incidents immediately",
          "Always follow company policies and procedures",
          "Use strong, unique passwords for all accounts",
          "Lock your computer when stepping away"
        ]
      },
      "ISP02": {
        title: "Legal Frameworks & Data Subject Rights",
        duration:"30min",
        videoUrl: "https://intern-vista-work-space.s3.eu-north-1.amazonaws.com/e-learning/Module_2+Course_1.mp4",
        content: [
          "Legal Framework Overview:",
          "",
          "Data protection laws establish rules for how organizations collect, use, store, and share personal information.",
          "",
          "Key Global Regulations:",
          "GDPR (General Data Protection Regulation) - European Union",
          "CCPA (California Consumer Privacy Act) - California, USA",
          "PIPEDA (Personal Information Protection and Electronic Documents Act) - Canada",
          "PDPA (Personal Data Protection Act) - Singapore, Thailand",
          "IT Act 2000 - India",
          "",
          "What is Personal Data?",
          "Any information that can identify a living individual",
          "Names, email addresses, phone numbers, ID numbers",
          "IP addresses, location data, online identifiers",
          "Biometric data, health records, financial information",
          "",
          "Data Subject Rights Under GDPR:",
          "Right to be Informed - Clear information about data processing",
          "Right of Access - Individuals can request copies of their personal data",
          "Right to Rectification - Correction of inaccurate or incomplete data",
          "Right to Erasure - 'Right to be forgotten' in certain circumstances",
          "Right to Restrict Processing - Limiting how data is used",
          "Right to Data Portability - Moving data between services",
          "Right to Object - Objecting to certain types of processing",
          "Rights related to Automated Decision Making - Including profiling",
          "",
          "Legal Bases for Processing:",
          "Consent - Clear, informed agreement from the individual",
          "Contract - Processing necessary for a contract with the individual",
          "Legal Obligation - Required by law",
          "Vital Interests - Protecting someone's life",
          "Public Task - Carrying out official functions",
          "Legitimate Interests - Balancing business needs with individual rights"
        ]
      },
      "ISP03": {
        title: "Risk Assessment & Threat Management",
        videoUrl: "https://intern-vista-work-space.s3.eu-north-1.amazonaws.com/e-learning/VISTA_Module_3+Course+2.mp4",
        content: [
          "Understanding Information Security Risks:",
          "",
          "A security risk is the potential for loss or damage when a threat exploits a vulnerability.",
          "",
          "Common Security Threats:",
          "Malware - Viruses, trojans, ransomware, spyware",
          "Phishing - Fraudulent emails designed to steal information",
          "Social Engineering - Manipulating people to divulge confidential information",
          "Insider Threats - Risks from employees, contractors, or business partners",
          "Physical Security Breaches - Unauthorized access to facilities or devices",
          "Data Breaches - Unauthorized access to sensitive information",
          "",
          "Risk Assessment Process:",
          "Identify Assets - What information and systems need protection",
          "Identify Threats - What could go wrong",
          "Assess Vulnerabilities - Weaknesses that could be exploited",
          "Determine Impact - Consequences if a threat occurs",
          "Calculate Risk - Likelihood × Impact = Risk Level",
          "Implement Controls - Measures to reduce risk",
          "",
          "Risk Management Strategies:",
          "Accept - Acknowledge the risk and take no action",
          "Avoid - Eliminate the activity that creates risk",
          "Mitigate - Reduce the likelihood or impact",
          "Transfer - Share or shift risk to another party",
          "",
          "Vulnerability Management:",
          "Regular security assessments and audits",
          "Keeping software and systems up to date",
          "Employee security awareness training",
          "Implementing security controls and monitoring",
          "Incident response planning and testing"
        ]
      },
      "ISP04": {
        title: "Security Controls & Best Practices",
        videoUrl: "https://intern-vista-work-space.s3.eu-north-1.amazonaws.com/e-learning/VISTA_Module_4+Course+2.mp4",
        content: [
          "Types of Security Controls:",
          "",
          "Administrative Controls:",
          "Security policies and procedures",
          "Employee background checks",
          "Security awareness training",
          "Access control policies",
          "Incident response procedures",
          "",
          "Technical Controls:",
          "Firewalls and intrusion detection systems",
          "Antivirus and anti-malware software",
          "Encryption for data at rest and in transit",
          "Multi-factor authentication",
          "Access control systems",
          "Security monitoring and logging",
          "",
          "Physical Controls:",
          "Locked doors and secure facilities",
          "Security cameras and monitoring",
          "Badge access systems",
          "Secure disposal of documents and devices",
          "Environmental controls (fire suppression, climate control)",
          "",
          "Password Security Best Practices:",
          "Use strong, unique passwords for each account",
          "Passwords should be at least 12 characters long",
          "Include uppercase, lowercase, numbers, and special characters",
          "Never share passwords with others",
          "Use a password manager to generate and store passwords",
          "Enable multi-factor authentication whenever possible",
          "",
          "Email Security:",
          "Be cautious of unexpected emails, even from known contacts",
          "Verify sender identity before clicking links or attachments",
          "Report suspicious emails to IT security team",
          "Use encrypted email for sensitive communications",
          "Keep email software updated",
          "",
          "Data Handling Best Practices:",
          "Follow the principle of least privilege",
          "Encrypt sensitive data both in storage and transmission",
          "Regularly backup important data",
          "Securely dispose of confidential information",
          "Use approved cloud services and storage solutions",
          "Monitor and log access to sensitive data"
        ]
      }
    }
  },
  "68789a19935761547602aef1": {
    name: "POSH",
    lessons: {
      "POSH01": {
        title: "Overview & Legal Foundation of POSH Act",
        videoUrl: "https://intern-vista-work-space.s3.eu-north-1.amazonaws.com/e-learning/POSH-module1.mp4",
        content: [
          "Introduction to POSH Act:",
          "",
          "The Sexual Harassment of Women at Workplace (Prevention, Prohibition and Redressal) Act, 2013 is a comprehensive legislation designed to protect women from sexual harassment at workplace.",
          "",
          "Legal Background:",
          "Based on the Vishaka Guidelines established by the Supreme Court in 1997",
          "Enacted to comply with international conventions on women's rights",
          "Mandated following India's commitment to eliminate discrimination against women",
          "",
          "Key Objectives:",
          "Prevent sexual harassment of women at workplace",
          "Provide redressal mechanism for complaints",
          "Create safe and secure work environment",
          "Ensure gender equality and women's right to work with dignity",
          "",
          "Scope and Applicability:",
          "All workplaces with 10 or more employees",
          "Both organized and unorganized sectors",
          "Government offices, private companies, NGOs",
          "Educational institutions, hospitals, sports facilities",
          "",
          "Who is Covered?",
          "All women employees, including regular, contractual, temporary staff",
          "Women working as consultants, volunteers, interns",
          "Domestic workers in households",
          "Women visiting workplace for any purpose",
          "",
          "Employer's Legal Obligations:",
          "Constitution of Internal Complaints Committee (ICC)",
          "Display of policies and procedures",
          "Conduct awareness programs",
          "Provide assistance to women filing complaints",
          "Take preventive measures to ensure harassment-free workplace"
        ]
      },
      "POSH02": {
        title: "Understanding Sexual Harassment: Definitions & Examples",
        videoUrl: "https://intern-vista-work-space.s3.eu-north-1.amazonaws.com/e-learning/POSH-module2.mp4",
        content: [
          "What Constitutes Sexual Harassment?",
          "",
          "Sexual harassment includes any unwelcome sexually determined behavior, whether directly or by implication.",
          "",
          "Physical Acts:",
          "Unwelcome physical contact and advances",
          "Physical confinement against one's will",
          "Any act of physical intimacy without consent",
          "Touching, grabbing, or brushing against someone inappropriately",
          "",
          "Verbal Harassment:",
          "Sexually suggestive comments or jokes",
          "Requests or demands for sexual favors",
          "Making sexual comments about appearance, clothing, or body",
          "Spreading sexual rumors or making sexual propositions",
          "Using sexually explicit or offensive language",
          "",
          "Visual Harassment:",
          "Displaying sexually explicit images, posters, or screensavers",
          "Sharing inappropriate photos or videos",
          "Making sexual gestures or facial expressions",
          "Sending explicit content via email or messages",
          "",
          "Psychological Harassment:",
          "Creating hostile work environment",
          "Repeated unwelcome social invitations",
          "Stalking or following someone",
          "Making threats related to employment based on sexual compliance",
          "",
          "Digital/Cyber Harassment:",
          "Sending unwelcome sexual messages via email, chat, or social media",
          "Sharing intimate images without consent",
          "Online stalking or monitoring",
          "Creating fake profiles to harass",
          "",
          "Quid Pro Quo Harassment:",
          "Explicit or implicit promise of preferential treatment in employment",
          "Threat of detrimental treatment for refusing sexual advances",
          "Making employment decisions based on submission to sexual conduct",
          "",
          "Important Points:",
          "Intent is not required - impact matters",
          "Single incident can constitute harassment if severe",
          "Pattern of behavior creates hostile environment",
          "Harassment can occur between any genders, though law specifically protects women"
        ]
      },
      "POSH03": {
        title: "Complaint Mechanism & Investigation Process",
        videoUrl: "https://intern-vista-work-space.s3.eu-north-1.amazonaws.com/e-learning/POSH_module3.mp4",
        content: [
          "Internal Complaints Committee (ICC):",
          "",
          "Composition of ICC:",
          "Presiding Officer - Senior woman employee",
          "Two members from amongst employees (at least one woman)",
          "One external member from NGO or familiar with women's issues",
          "Minimum 50% members should be women",
          "",
          "Qualifications of ICC Members:",
          "Knowledge or experience in social work or legal issues",
          "Commitment to protect women's rights",
          "No conflict of interest with the organization",
          "Training in handling sexual harassment cases",
          "",
          "How to File a Complaint:",
          "Written complaint within 3 months of incident",
          "Extension possible up to 6 months with sufficient cause",
          "Complaint can be made by victim or on her behalf",
          "Anonymous complaints not accepted",
          "",
          "Information to Include in Complaint:",
          "Name and address of complainant",
          "Name and address of respondent",
          "Statement of circumstances of alleged incident",
          "Dates, times, and locations of incidents",
          "Names and contact details of witnesses",
          "Any supporting documents or evidence",
          "",
          "Investigation Process:",
          "ICC must commence inquiry within 7 days of complaint",
          "Complete investigation within 90 days",
          "Both parties have right to be heard",
          "Opportunity to examine witnesses and documents",
          "Confidentiality maintained throughout process",
          "",
          "Interim Relief Measures:",
          "Transfer of complainant or respondent",
          "Grant leave to complainant",
          "Restrain respondent from reporting on complainant's performance",
          "Any other measure deemed appropriate",
          "",
          "Investigation Report:",
          "ICC submits report within 10 days of completion",
          "Recommendations for action if harassment proved",
          "Copy provided to both parties",
          "Employer must act within 60 days of receiving report"
        ]
      },
      "POSH04": {
        title: "Rights, Responsibilities & Creating Safe Workplace",
        videoUrl: "https://intern-vista-work-space.s3.eu-north-1.amazonaws.com/e-learning/POSH-module4.mp4",
        content: [
          "Rights of Women Employees:",
          "",
          "Right to Safe Workplace:",
          "Work environment free from sexual harassment",
          "Protection from retaliation for filing complaints",
          "Right to privacy and confidentiality during proceedings",
          "Access to support and counseling services",
          "",
          "Right to Fair Process:",
          "Impartial and time-bound inquiry",
          "Opportunity to present case and evidence",
          "Right to cross-examine witnesses",
          "Protection of identity during investigation",
          "",
          "Responsibilities of All Employees:",
          "",
          "Create Respectful Environment:",
          "Treat all colleagues with dignity and respect",
          "Maintain professional behavior at all times",
          "Respect personal boundaries and space",
          "Avoid making offensive jokes or comments",
          "",
          "Be an Active Bystander:",
          "Speak up against inappropriate behavior",
          "Support colleagues who face harassment",
          "Report incidents you witness",
          "Create inclusive workplace culture",
          "",
          "Management Responsibilities:",
          "",
          "Prevention Measures:",
          "Develop and implement anti-harassment policies",
          "Conduct regular awareness and training programs",
          "Display policy information prominently",
          "Monitor workplace climate and culture",
          "",
          "Response to Complaints:",
          "Ensure timely and fair investigation",
          "Take appropriate disciplinary action",
          "Provide support to complainants",
          "Monitor for retaliation and prevent it",
          "",
          "Creating Safe Workplace Culture:",
          "",
          "Leadership Commitment:",
          "Clear message from top management",
          "Zero tolerance policy for harassment",
          "Regular communication about expectations",
          "Leading by example in behavior",
          "",
          "Training and Awareness:",
          "Regular POSH training for all employees",
          "Specialized training for ICC members",
          "New employee orientation on policies",
          "Refresher training and updates",
          "",
          "Communication and Reporting:",
          "Multiple channels for reporting complaints",
          "Anonymous reporting options where possible",
          "Regular surveys on workplace climate",
          "Open door policies for concerns",
          "",
          "Consequences of Non-Compliance:",
          "Fine up to ₹50,000 for first violation",
          "Higher penalties for repeat violations",
          "Cancellation or non-renewal of license",
          "Individual liability for responsible officers"
        ]
      }
    }
  },
  "68885822d486bba2975cdca2": {
    name: "GDPR",
    lessons: {
      "GDPR01": {
        title: "Basics of GDPR & Information Security",
        videoUrl: "https://intern-vista-work-space.s3.eu-north-1.amazonaws.com/e-learning/Module+1_Course_1.mp4",
        content: [
          "What is GDPR?",
          "",
          "The General Data Protection Regulation (GDPR) is a comprehensive data protection law that came into effect on May 25, 2018, replacing the Data Protection Directive 95/46/EC.",
          "",
          "Global Scope and Applicability:",
          "Applies to all EU member states",
          "Affects any organization processing EU residents' personal data",
          "Applies regardless of where the organization is based",
          "Covers both data controllers and data processors",
          "",
          "What is Personal Data Under GDPR?",
          "Any information relating to an identified or identifiable natural person",
          "Names, identification numbers, location data",
          "Online identifiers, email addresses, IP addresses",
          "Physical, physiological, genetic, mental, economic, cultural, or social identity factors",
          "",
          "Special Categories of Personal Data:",
          "Racial or ethnic origin",
          "Political opinions and religious beliefs",
          "Trade union membership",
          "Genetic and biometric data",
          "Health data and data concerning sex life",
          "Sexual orientation",
          "",
          "Key GDPR Principles:",
          "Lawfulness, Fairness, and Transparency",
          "Purpose Limitation - Data collected for specific, legitimate purposes",
          "Data Minimisation - Adequate, relevant, and limited to what is necessary",
          "Accuracy - Data must be accurate and up to date",
          "Storage Limitation - Kept only as long as necessary",
          "Integrity and Confidentiality - Appropriate security measures",
          "Accountability - Demonstrate compliance with principles",
          "",
          "Information Security Under GDPR:",
          "Data protection by design and by default",
          "Appropriate technical and organizational measures",
          "Regular testing and evaluation of security effectiveness",
          "Encryption and pseudonymization where appropriate",
          "",
          "Why Everyone is Responsible:",
          "GDPR compliance requires organization-wide commitment",
          "Every employee handles personal data in some capacity",
          "Individual actions can lead to regulatory violations",
          "Personal accountability for data protection roles"
        ]
      },
      "GDPR02": {
        title: "Principles, Rights & Responsibilities",
        videoUrl: "https://intern-vista-work-space.s3.eu-north-1.amazonaws.com/e-learning/Module_2+Course_1.mp4",
        content: [
          "Lawful Bases for Processing Personal Data:",
          "",
          "Six Lawful Bases Under GDPR:",
          "Consent - Freely given, specific, informed, and unambiguous",
          "Contract - Processing necessary for contract performance",
          "Legal Obligation - Required by law",
          "Vital Interests - Protecting life or physical safety",
          "Public Task - Carrying out official functions",
          "Legitimate Interests - Balancing test with individual rights",
          "",
          "Understanding Consent:",
          "Must be freely given - no coercion or detriment",
          "Specific - clearly state what data and purposes",
          "Informed - provide clear information about processing",
          "Unambiguous - clear affirmative action required",
          "Withdrawable - as easy to withdraw as to give",
          "",
          "Individual Rights Under GDPR:",
          "",
          "Right to be Informed:",
          "Clear information about data processing",
          "Purpose of processing and legal basis",
          "How long data will be retained",
          "Who data will be shared with",
          "",
          "Right of Access:",
          "Confirm whether personal data is being processed",
          "Access to the personal data",
          "Additional information about processing",
          "Response required within one month",
          "",
          "Right to Rectification:",
          "Correct inaccurate personal data",
          "Complete incomplete personal data",
          "Response within one month",
          "Notify third parties of changes where possible",
          "",
          "Right to Erasure ('Right to be Forgotten'):",
          "When personal data no longer necessary",
          "Consent is withdrawn and no other lawful basis",
          "Data unlawfully processed",
          "Required for legal compliance",
          "",
          "Right to Restrict Processing:",
          "When accuracy is contested",
          "Processing is unlawful but erasure not wanted",
          "Data no longer needed but required for legal claims",
          "Objection to processing pending verification",
          "",
          "Employee Responsibilities:",
          "",
          "Data Handling:",
          "Only process data for legitimate business purposes",
          "Follow data minimization principles",
          "Ensure data accuracy and keep it updated",
          "Delete data when no longer needed",
          "",
          "Security Measures:",
          "Use strong passwords and lock computers when away",
          "Never share login credentials",
          "Report security incidents immediately",
          "Only use approved systems and software",
          "Encrypt sensitive data when required",
          "",
          "Privacy by Design:",
          "Consider privacy implications in all activities",
          "Implement appropriate safeguards from the start",
          "Document processing activities and decisions",
          "Conduct privacy impact assessments when required"
        ]
      },
      "GDPR03": {
        title: "Safe Practices & Company Policies",
        videoUrl: "https://intern-vista-work-space.s3.eu-north-1.amazonaws.com/e-learning/Module_3+Course_1.mp4",
        content: [
          "Technical Safeguards:",
          "",
          "Device and System Security:",
          "Use only company-approved devices for business data",
          "Install approved software and keep systems updated",
          "Enable automatic screen locks with secure passwords",
          "Use company-provided VPN for remote access",
          "Never save business data to personal devices or accounts",
          "",
          "Data Encryption:",
          "Encrypt sensitive data both at rest and in transit",
          "Use secure communication channels for confidential information",
          "Implement full-disk encryption on laptops and mobile devices",
          "Use encrypted email for sensitive communications",
          "",
          "Access Controls:",
          "Follow principle of least privilege",
          "Use multi-factor authentication where available",
          "Regularly review and update access permissions",
          "Promptly revoke access for departing employees",
          "",
          "Physical Security Measures:",
          "",
          "Document Security:",
          "Store physical documents in locked filing cabinets",
          "Use secure disposal methods for confidential papers",
          "Never leave sensitive documents unattended",
          "Implement clean desk policy",
          "",
          "Workspace Security:",
          "Lock computer screens when away from desk",
          "Position screens away from public view",
          "Secure physical access to work areas",
          "Properly dispose of storage media",
          "",
          "Remote Work Guidelines:",
          "",
          "Home Office Security:",
          "Ensure private workspace for confidential calls",
          "Secure home Wi-Fi networks",
          "Use company VPN for all business activities",
          "Store business documents securely",
          "",
          "Travel Considerations:",
          "Never leave devices unattended in vehicles or public spaces",
          "Use privacy screens in public areas",
          "Avoid connecting to unsecured public Wi-Fi",
          "Be mindful of shoulder surfing",
          "",
          "Company Data Protection Policies:",
          "",
          "Role of Data Protection Officer (DPO):",
          "Monitor GDPR compliance within organization",
          "Conduct privacy impact assessments",
          "Serve as point of contact for data subjects and regulators",
          "Provide training and guidance to staff",
          "",
          "Data Processing Records:",
          "Maintain records of processing activities",
          "Document lawful bases for processing",
          "Keep records of data sharing with third parties",
          "Track data retention periods",
          "",
          "Third-Party Management:",
          "Ensure vendors have appropriate data protection measures",
          "Use data processing agreements for service providers",
          "Monitor third-party compliance with GDPR",
          "Limit data sharing to what is necessary",
          "",
          "Training and Awareness:",
          "Regular GDPR training for all staff",
          "Role-specific privacy training",
          "Updates on regulatory changes",
          "Privacy awareness campaigns"
        ]
      },
      "GDPR04": {
        title: "Breaches, Penalties & Real Cases",
        videoUrl: "https://intern-vista-work-space.s3.eu-north-1.amazonaws.com/e-learning/Module_4+Course_1.mp4",
        content: [
          "Understanding Data Breaches:",
          "",
          "What Constitutes a Data Breach?",
          "Any security incident that leads to accidental or unlawful destruction, loss, alteration, unauthorized disclosure, or access to personal data",
          "Not just cyber attacks - includes human error and system failures",
          "Can involve any type of personal data, not just sensitive data",
          "",
          "Types of Data Breaches:",
          "Confidentiality breach - unauthorized disclosure or access",
          "Integrity breach - unauthorized alteration of data",
          "Availability breach - accidental or unauthorized loss or destruction",
          "",
          "Common Breach Scenarios:",
          "Cyber attacks and hacking incidents",
          "Email sent to wrong recipients",
          "Lost or stolen devices containing personal data",
          "Unauthorized access by employees",
          "System failures and technical errors",
          "Physical theft of documents",
          "",
          "Breach Notification Requirements:",
          "",
          "72-Hour Rule:",
          "Must notify supervisory authority within 72 hours of becoming aware",
          "If delay exceeds 72 hours, must provide reasons",
          "Notification even if ongoing investigation",
          "Follow-up information can be provided later",
          "",
          "What to Include in Notification:",
          "Nature of the personal data breach",
          "Categories and approximate number of data subjects affected",
          "Categories and approximate number of records affected",
          "Name and contact details of Data Protection Officer",
          "Likely consequences of the breach",
          "Measures taken or proposed to address the breach",
          "",
          "Individual Notification:",
          "Required when breach likely to result in high risk",
          "Must be communicated without undue delay",
          "Use clear and plain language",
          "Provide advice on protective measures",
          "",
          "GDPR Penalties and Fines:",
          "",
          "Two-Tier Penalty Structure:",
          "Lower tier - Up to €10 million or 2% of annual worldwide turnover",
          "Higher tier - Up to €20 million or 4% of annual worldwide turnover",
          "",
          "Factors Considered for Penalties:",
          "Nature, gravity, and duration of infringement",
          "Intentional or negligent character of infringement",
          "Categories of personal data affected",
          "Cooperation with supervisory authority",
          "Previous infringements and compliance history",
          "Technical and organizational measures implemented",
          "",
          "Real-World Case Studies:",
          "",
          "British Airways (2019):",
          "Fine: £183 million (later reduced to £20 million)",
          "Breach affected 500,000 customers",
          "Insufficient security measures identified",
          "",
          "Marriott International (2020):",
          "Fine: £99 million (later reduced to £18.4 million)",
          "Breach exposed 339 million guest records",
          "Failed to implement appropriate technical measures",
          "",
          "Google (2019):",
          "Fine: €50 million",
          "Lack of transparency and valid consent",
          "Insufficient information provided to users",
          "",
          "Key Lessons Learned:",
          "Proactive security measures are essential",
          "Regular security audits and updates required",
          "Employee training is crucial",
          "Swift incident response reduces penalties",
          "Cooperation with regulators is valued",
          "",
          "Do's and Don'ts Summary:",
          "",
          "DO:",
          "Report suspected breaches immediately",
          "Follow company incident response procedures",
          "Document all actions taken during breach response",
          "Cooperate fully with investigations",
          "Learn from incidents to improve security",
          "",
          "DON'T:",
          "Try to handle breaches independently",
          "Delay reporting to minimize impact",
          "Assume small incidents don't matter",
          "Ignore security warnings or alerts",
          "Underestimate the importance of employee training"
        ]
      }
    }
  },
  "68885a71d486bba2975cdca4": {
    name: "Factory Act",
    lessons: {
      "FACT01": {
        title: "Introduction to Factory Act",
        videoUrl: "https://intern-vista-work-space.s3.eu-north-1.amazonaws.com/e-learning/Module_2+Course_1.mp4",
        content: [
          "Overview of the Factories Act:",
          "",
          "The Factories Act, 1948 is a comprehensive legislation designed to regulate working conditions, ensure worker safety, and promote welfare in manufacturing establishments across India.",
          "",
          "Historical Background:",
          "First enacted in 1881, extensively revised in 1948",
          "Based on International Labour Organization (ILO) conventions",
          "Reflects India's commitment to worker rights and industrial safety",
          "Regularly amended to address emerging industrial challenges",
          "",
          "Purpose and Objectives:",
          "Ensure safe and healthy working conditions",
          "Regulate working hours and overtime",
          "Provide welfare facilities for workers",
          "Prevent exploitation of industrial workers",
          "Establish standards for factory operations",
          "",
          "Scope and Applicability:",
          "",
          "What Constitutes a Factory?",
          "Any premises where 10 or more workers work with power",
          "Or 20 or more workers work without power",
          "Manufacturing processes are carried out",
          "Includes seasonal factories operating 180+ days per year",
          "",
          "Types of Factories Covered:",
          "Manufacturing and production units",
          "Processing industries",
          "Assembly plants",
          "Repair and maintenance workshops",
          "Mining operations (certain provisions)",
          "",
          "Excluded Establishments:",
          "Mines (covered under Mines Act)",
          "Mobile units of armed forces",
          "Railways running sheds",
          "Hotels and restaurants (unless manufacturing)",
          "",
          "Key Stakeholders and Responsibilities:",
          "",
          "Factory Owner/Occupier:",
          "Ensure compliance with all provisions",
          "Obtain necessary licenses and approvals",
          "Provide safe working conditions",
          "Implement welfare measures",
          "Maintain required records and registers",
          "",
          "Factory Manager:",
          "Day-to-day implementation of safety measures",
          "Supervise compliance with working hour limits",
          "Coordinate with factory inspectors",
          "Ensure proper maintenance of machinery",
          "",
          "Workers' Responsibilities:",
          "Follow safety protocols and procedures",
          "Use protective equipment provided",
          "Report unsafe conditions or accidents",
          "Cooperate with safety training programs",
          "",
          "State Government Role:",
          "Appoint factory inspectors",
          "Issue licenses and approvals",
          "Enforce compliance and penalties",
          "Modify rules based on local conditions",
          "",
          "Registration and Licensing:",
          "",
          "Mandatory Registrations:",
          "Factory license before commencing operations",
          "Registration with appropriate authorities",
          "Approval for building plans and layouts",
          "Environmental clearances where required",
          "",
          "Documentation Required:",
          "Factory layout plans and drawings",
          "Details of manufacturing processes",
          "Machinery specifications and safety features",
          "Worker capacity and employment details",
          "Emergency response and safety plans"
        ]
      },
      "FACT03": {
        title: "Legal Compliance & Inspections",
        videoUrl: "https://intern-vista-work-space.s3.eu-north-1.amazonaws.com/e-learning/Module_2+Course_1.mp4",
        content: [
          "Role of factory inspectors and frequency of inspections.",
          "Common violations and penalties.",
          "Maintaining records and documentation compliance."
        ]
      },
      "FACT04": {
        title: "Employee Rights & Grievance Redressal",
        videoUrl: "https://intern-vista-work-space.s3.eu-north-1.amazonaws.com/e-learning/Module_2+Course_1.mp4",
        content: [
          "Rights of factory workers under the Act.",
          "Process for addressing complaints and grievances.",
          "Safety training and representation in safety committees."
        ]
      }
    }
  },
  "68885c86d486bba2975cdca6": {
    name: "Welding",
    lessons: {
      "WELD01": {
        title: "Basics of Industrial Work Skills",
        videoUrl: "https://intern-vista-work-space.s3.eu-north-1.amazonaws.com/e-learning/Module_2+Course_1.mp4",
        content: [
          "Introduction to Industrial Work Environment:",
          "",
          "Understanding the Mechanical Shop Floor:",
          "Layout and organization of industrial workspaces",
          "Different work zones: welding, machining, assembly, storage",
          "Material flow and workflow optimization",
          "Housekeeping standards and 5S methodology",
          "Communication protocols in industrial settings",
          "",
          "Overview of Job Roles and Career Paths:",
          "",
          "Welding Positions:",
          "Arc Welder - Manual metal arc welding operations",
          "TIG Welder - Precision tungsten inert gas welding",
          "MIG Welder - Metal inert gas welding specialist",
          "Pipe Welder - Specialized pipeline and structural welding",
          "Welding Inspector - Quality control and certification",
          "",
          "CNC Operations:",
          "CNC Operator - Machine operation and basic programming",
          "CNC Programmer - Advanced program development",
          "CNC Setup Technician - Machine preparation and tooling",
          "CNC Maintenance Technician - Equipment servicing",
          "",
          "Fitting and Assembly:",
          "Mechanical Fitter - Component assembly and alignment",
          "Precision Fitter - High-accuracy mechanical work",
          "Maintenance Fitter - Equipment repair and servicing",
          "Quality Inspector - Measurement and testing",
          ""
        ]
      },
      "WELD02": {
        title: "Welding & Safety Guidelines",
        videoUrl: "https://intern-vista-work-space.s3.eu-north-1.amazonaws.com/e-learning/Module_2+Course_1.mp4",
        content: [
           "Welding Process Overview:",
          "",
          "Shielded Metal Arc Welding (SMAW/Stick):",
          "Basic principle and equipment setup",
          "Electrode types and selection criteria",
          "Current settings for different materials",
          "Joint preparation and fit-up requirements",
          "Welding positions: flat, horizontal, vertical, overhead",
          "Common defects and prevention methods",
          "Applications in structural and maintenance welding",
          "",
          "Gas Metal Arc Welding (GMAW/MIG):",
          "Equipment components and gas selection",
          "Wire feed speed and voltage relationships",
          "Short circuit, globular, and spray transfer modes",
          "Aluminum, stainless steel, and carbon steel welding",
          "Pulsed MIG welding advantages",
          "Travel speed and technique optimization",
          "",
          "Gas Tungsten Arc Welding (GTAW/TIG):",
          "Tungsten electrode types and preparation",
          "Shielding gas selection and flow rates",
          "AC vs DC welding applications",
          "Filler metal selection and feeding techniques",
          "Precision welding on thin materials",
          "Exotic materials and aerospace applications",
          "",
          "Flux-Cored Arc Welding (FCAW):",
          "Self-shielded vs. gas-shielded flux-cored wires",
          "Higher deposition rates and productivity",
          "Outdoor welding applications",
          "Structural steel and heavy fabrication uses",
          "",
          "Specialized Welding Processes:",
          "Submerged Arc Welding (SAW) for heavy sections",
          "Plasma Arc Welding (PAW) for precision work",
          "Resistance welding for sheet metal",
          "Brazing and soldering applications"
        ]
      },
      "WELD03": {
        title: "CNC Operations Overview",
        videoUrl: "https://intern-vista-work-space.s3.eu-north-1.amazonaws.com/e-learning/Module_2+Course_1.mp4",
        content: [
          "Advanced Welding Joint Design:",
          "",
          "Joint Types and Applications:",
          "Butt joints for structural connections",
          "Fillet joints for corner and T-connections",
          "Groove joints for full penetration welds",
          "Lap joints for overlapping materials",
          "Edge joints for sheet metal work",
          "",
          "Joint Preparation Techniques:",
          "Cutting and beveling procedures",
          "Root opening and backing bar use",
          "Fit-up tolerance requirements",
          "Tack welding strategies",
          "Preheating requirements for thick sections",
          "",
          "Welding Metallurgy Fundamentals:",
          "",
          "Heat Affected Zone (HAZ):",
          "Understanding HAZ formation and properties",
          "Grain growth and hardening effects",
          "Controlling HAZ size through heat input",
          "Post-weld heat treatment considerations",
          "",
          "Material Properties:",
          "Carbon content effects on weldability",
          "Alloy elements and their influence",
          "Thermal expansion and distortion control",
          "Residual stress development and relief",
          "",
          "Advanced Welding Positions:",
          "",
          "Vertical Welding Techniques:",
          "Uphill vs. downhill progression",
          "Weave patterns and manipulation",
          "Current and travel speed adjustments",
          "Controlling molten pool behavior",
          "",
          "Overhead Welding Mastery:",
          "Safety considerations for overhead work",
          "Electrode angle and manipulation",
          "Spatter control and cleanup",
          "Fatigue management during overhead welding",
          "",
          "Pipe Welding Fundamentals:",
          "Pipe joint preparation and alignment",
          "Root pass welding techniques",
          "Hot pass and fill pass procedures",
          "Cap pass finishing methods",
          "Rolling vs. fixed position welding"
        ]
      },
      "WELD04": {
        title: "Fitting Techniques & Maintenance",
        videoUrl: "https://intern-vista-work-space.s3.eu-north-1.amazonaws.com/e-learning/Module_2+Course_1.mp4",
        content: [
           "Welding Equipment Components:",
          "",
          "Power Source Maintenance:",
          "Cleaning cooling system components",
          "Inspecting and replacing filters",
          "Checking electrical connections and torque",
          "Calibrating voltage and amperage settings",
          "Troubleshooting common power source issues",
          "",
          "Wire Feed System Care:",
          "Drive roll selection and adjustment",
          "Liner replacement and sizing",
          "Contact tip maintenance and replacement",
          "Gun cable and connection inspection",
          "Wire feed speed calibration",
          "",
          "Gas System Maintenance:",
          "Regulator and flowmeter calibration",
          "Hose inspection and replacement",
          "Leak testing procedures",
          "Gas quality and contamination issues",
          "Proper storage and handling of gas cylinders",
          "",
          "Preventive Maintenance Schedules:",
          "",
          "Daily Maintenance Tasks:",
          "Visual inspection of equipment condition",
          "Cleaning spatter from gun and cables",
          "Checking consumable levels and condition",
          "Verifying proper gas flow and pressure",
          "Recording any unusual observations"
        ]
      }
    }
  },
"68885cf5d486bba2975cdca8": {
  
  name: "CNC",
  description: "Computer Numerical Control machine operation and programming training.",
  level: "Intermediate",
  backgroundImage: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=400&h=2…",
  lessons: {
    "CNC01": {
      m_id: "CNC01",
      _id: "68789a19935761547602b401",
      title: "Introduction to CNC Machines",
      duration: 40,
      description: "Understand the basics of CNC machines, their types, and applications in modern manufacturing.",
      videoUrl: "https://intern-vista-work-space.s3.eu-north-1.amazonaws.com/e-learning/Module_2+Course_1.mp4",
      content: [
        "Understanding CNC Technology:",
          "",
          "What is Computer Numerical Control (CNC)?",
          "Automated machine tool control through computer programs",
          "Precise, repeatable manufacturing processes",
          "Integration of computer technology with machine tools",
          "Evolution from manual machining to automated systems",
          "",
          "Historical Development:",
          "Origins in 1940s-1950s with punch tape systems",
          "Development of computer-based controls in 1960s-1970s",
          "Modern CNC systems with advanced software",
          "Future trends: AI, IoT, and Industry 4.0 integration",
          "",
          "Role in Modern Manufacturing:",
          "Mass production with consistent quality",
          "Complex geometry machining capabilities",
          "Reduced labor costs and human error",
          "24/7 production capabilities with automation",
          "Integration with CAD/CAM systems",
          "",
          "Types of CNC Machine Tools:",
          "",
          "CNC Milling Machines:",
          "Vertical milling machines for general machining",
          "Horizontal milling machines for heavy cutting",
          "5-axis milling for complex geometries",
          "High-speed milling for finishing operations",
          "Applications: aerospace, automotive, tooling"
      ]
    },
    "CNC02": {
      m_id: "CNC02",
      _id: "68789a19935761547602b402",
      title: "CNC Programming Fundamentals",
      duration: 50,
      description: "Learn basic G-code programming and machine control operations.",
      videoUrl: "https://intern-vista-work-space.s3.eu-north-1.amazonaws.com/e-learning/Module_2+Course_1.mp4",
      content: [
         "CNC Programming Language Overview:",
          "",
          "Understanding G-Code Structure:",
          "Program format and line numbering (N codes)",
          "Block structure and word addresses",
          "Modal vs. non-modal commands",
          "Program organization and flow",
          "Comments and documentation within programs",
          "",
          "Coordinate Systems and Reference Points:",
          "",
          "Machine Coordinate System (MCS):",
          "Machine home position and reference points",
          "Machine axes designation (X, Y, Z, A, B, C)",
          "Machine limits and travel ranges",
          "Home positioning and zero return",
          "",
          "Workpiece Coordinate System (WCS):",
          "Work offsets (G54-G59) and their applications",
          "Part zero location and setup",
          "Coordinate system rotation and scaling",
          "Multiple workpiece coordinate systems"
      ]
    },
    "CNC03": {
      m_id: "CNC03",
      title: "Advanced CNC Operations",
      duration: 30,
      description: "Master complex operations and troubleshooting techniques.",
      videoUrl: "https://intern-vista-work-space.s3.eu-north-1.amazonaws.com/e-learning/Module_2+Course_1.mp4",
      content: [
       "Advanced Machining Strategies:",
          "",
          "High-Speed Machining (HSM):",
          "Principles of high-speed cutting",
          "Spindle speed and feed rate relationships",
          "Toolpath strategies for HSM",
          "Machine requirements and capabilities",
          "Benefits: reduced cutting forces, better surface finish",
          "Applications in aerospace and automotive industries",
          "",
          "High-Efficiency Milling:",
          "Adaptive clearing strategies",
          "Optimal chip load maintenance",
          "Variable feed rate programming",
          "Tool engagement angle control",
          "Maximizing material removal rates",
          "",
          "Finish Machining Techniques:",
          "Surface finish optimization",
          "Scallop height and step-over calculations",
          "Parallel, radial, and spiral finishing",
          "Contour milling strategies",
          "Rest machining for complex geometries"
      ]
    },
    "CNC04": {
      m_id: "CNC04",
      title: "CNC Maintenance & Troubleshooting",
      duration: 35,
      description: "Learn preventive maintenance and common problem-solving.",
      videoUrl: "https://intern-vista-work-space.s3.eu-north-1.amazonaws.com/e-learning/Module_2+Course_1.mp4",
      content: [
       "Preventive Maintenance Fundamentals:",
          "",
          "Understanding Machine Components:",
          "Mechanical systems: spindles, ball screws, linear guides",
          "Electrical systems: servo motors, encoders, control panels",
          "Hydraulic systems: pumps, cylinders, pressure regulators",
          "Pneumatic systems: compressors, valves, air filters",
          "Coolant systems: pumps, filtration, temperature control",
          "",
          "Daily Maintenance Procedures:",
          "",
          "Pre-Operation Checks:",
          "Visual inspection of machine condition",
          "Lubrication system operation verification",
          "Coolant level and condition assessment",
          "Air pressure and hydraulic pressure checks",
          "Safety system functionality testing",
          "Chip removal and workspace cleaning",
          "",
          "Operating Condition Monitoring:",
          "Unusual noise or vibration detection",
          "Temperature monitoring of critical components",
          "Cutting tool condition assessment",
          "Workpiece quality and dimensional accuracy",
          "Cycle time and performance tracking",
          "",
          "Post-Operation Procedures:",
          "Complete chip removal and cleaning",
          "Coolant system shutdown and drainage if required",
          "Tool condition documentation",
          "Machine position and axis parking",
          "Power-down sequence and securing",
          "",
          "Weekly Maintenance Tasks:",
          "",
          "Lubrication System Service:",
          "Automatic lubrication system inspection",
          "Manual lubrication of specified points",
          "Lubricant level checking and replenishment",
          "Grease fitting service and cleaning",
                    "Oil analysis and condition monitoring"
        ]
      }
    }
  },
  "68885cf5d486bba2975cdca9": {
  "name": "VRU",
  "description": "Training on identifying and annotating Vulnerable Road Users (pedestrians) in various scenarios with proper bounding box techniques and attribute labeling.",
  "level": "Intermediate",
  "backgroundImage": "https://images.unsplash.com/photo-1508898578281-774ac4893c0d?w=400&h=200&fit=crop",
  "lessons": {
    "VRU01": {
      "m_id": "VRU01",
      "_id": "68789a19935761547602b501",
      "title": "Definition & Exclusions",
      "duration": 25,
      "description": "Learn what qualifies as a pedestrian, and the specific cases that should be excluded from labeling.",
      "videoUrl": "https://intern-vista-work-space.s3.eu-north-1.amazonaws.com/e-learning/VRU_Module_1.mp4",
      "content": [
        "Definition of Pedestrian:",
        "",
        "A pedestrian is any person who is walking, running, standing, or otherwise on foot in the scene.",
        "This includes people crossing streets, walking along sidewalks, or standing in open areas.",
        "",
        "Exclusions:",
        "Do not label individuals inside vehicles (drivers, passengers).",
        "Do not label reflections of people in mirrors or windows.",
        "Do not label people fully visible in posters, billboards, or digital displays.",
        "",
        "Special Note:",
        "People partially inside a vehicle but with significant body parts outside should be labeled only if their position is relevant to scene context.",
        "Do not label mannequins or non-living human-shaped objects."
      ]
    },
    "VRU02": {
      "m_id": "VRU02",
      "_id": "68789a19935761547602b502",
      "title": "Bounding Box Rules",
      "duration": 30,
      "description": "Understand how to draw accurate bounding boxes for pedestrians, including occlusion and perspective handling.",
      "videoUrl": "https://intern-vista-work-space.s3.eu-north-1.amazonaws.com/e-learning/VRU_Module_2.mp4",
      "content": [
        "Bounding Box Guidelines:",
        "",
        "Draw the box from the top of the head (including hats or helmets) to the bottom of the feet.",
        "Include carried items such as backpacks if they are closely attached to the person.",
        "Exclude objects that are not directly attached (e.g., trolleys, bicycles).",
        "",
        "Multiple People in Close Proximity:",
        "Draw separate bounding boxes for each visible individual, even if partially occluded.",
        "For people carrying children, the child must be labeled separately as a pedestrian.",
        "",
        "Perspective Considerations:",
        "When people are partially outside the frame, draw the bounding box to the visible extent.",
        "Boxes should align tightly without cutting off visible body parts."
      ]
    },
    "VRU03": {
      "m_id": "VRU03",
      "_id": "68789a19935761547602b503",
      "title": "Special Cases & Linking",
      "duration": 20,
      "description": "Learn how to handle unusual labeling cases and link pedestrians to other objects when necessary.",
      "videoUrl": "https://intern-vista-work-space.s3.eu-north-1.amazonaws.com/e-learning/VRU_Module_3.mp4",
      "content": [
        "Labeling Billboards & Statues:",
        "",
        "Do not label people in posters, billboards, or statues — use 'isIgnoreArea' instead.",
        "",
        "Linking to Other Objects:",
        "Use 'isAttachedTo' when a pedestrian is physically connected to another labeled object (e.g., holding a labeled bicycle, pushing a stroller).",
        "",
        "Labeling on Stairs or Elevated Surfaces:",
        "Ensure bounding boxes follow the same head-to-foot rule even if the person is on stairs or elevated areas.",
        "Adjust box position to match the person’s standing level, not the ground floor."
      ]
    },
    "VRU04": {
      "m_id": "VRU04",
      "_id": "68789a19935761547602b504",
      "title": "Properties & Attributes",
      "duration": 35,
      "description": "Identify and annotate pedestrian attributes including duty, group behavior, age, clothing, and posture.",
      "videoUrl": "https://intern-vista-work-space.s3.eu-north-1.amazonaws.com/e-learning/VRU_Module_4.mp4",
      "content": [
        "Pedestrian Attributes:",
        "",
        "Duty - Mark if the person is working (e.g., traffic police, construction worker).",
        "isDummy - Mark for mannequins or artificial figures.",
        "Occlusion - Indicate percentage of the pedestrian that is hidden.",
        "isGroup - Mark if the pedestrian is part of a group walking together.",
        "",
        "Additional Attributes:",
        "Age - Classify as Child, Adult, or Senior.",
        "Clothing - Indicate if wearing uniforms, reflective vests, or protective gear.",
        "Accessories - Label visible items like umbrellas, shopping bags, hats.",
        "Posture - Standing, walking, running, sitting, lying down."
      ]
    }
  }
}
};

export default courseData;



